// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:leitner_app/models/app_settings.dart';
import 'package:leitner_app/models/flashcard.dart';
import 'package:leitner_app/models/study_log.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(FlashcardAdapter());
    registerAdapter(StudyLogAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(FlashcardAdapter());
    registerAdapter(StudyLogAdapter());
  }
}
